### ISSUE TITLE
[Feature Request] better chat formatting colors

### ISSUE THREAD

**Issue by refact0r** [oddlama/vane#194]
So it seems like the vane-admin chat formatting forces all chat messages to have an aqua sender name and gray text. Gray is harder to read so it would be better if white was the default. Also, the chat should support team colors (from /team) on the sender name instead of just aqua. It would be great if these colors could be customized.

**Comment by oddlama** [comment]
On Java I personally find it a lot more readable (which is why it exists I guess), but of course it's a matter of taste. I really didn't want to introduce a lot of complexity here since then users want all kind of stuff (permissions levels, colored prefixes, special overrides, database queried names), and I think this is not something that should be part of vane.
If you want a specific format, just disable vane's internal formatter `vane-admin/config.yml` -> `chat_message_formatter` and use a more sophisticated plugin.
