### ISSUE TITLE
North compass showing random locations

### ISSUE THREAD

**Issue by WaxenSs** [oddlama/vane#198]
When the north compass is on one hand, [the indication showing random locations](https://github.com/oddlama/vane/assets/37812331/03e9addd-e792-4308-afef-cc29890a5e8d)

MC Version: 1.20.1 
Paper Version: 1.20.1-18

I tried to :
- Craft the item manually instead of using the `/customitem` command = same problem
- Craft the item manually in `survival mode` = same problem
- I've noticed that the north compass only works when the item has just been crafted and is not yet in the player's inventory.

**Comment by WaxenSs** [comment]
Ok I just unintentionally drop the compass, and from the moment I got it back, it started working normally, strange 🤔
And that's not all, now when I craft another north compass, the problem is gone.
Throwing the compass away and picking it up again fixes the bug 🤯

**Comment by oddlama** [comment]
Yeah the north compass requires some hacky tricks and thus can get a little weird. The issue is that minecraft doesn't support a north compass per-se, so set a location in the current world that is at `0,-999999999` (very far north) so for all practical purposes it will be north.

If you change world etc, this location needs to be updated, and we are doing that by resetting the location on certain events. So picking it up fixes it :P  What's more interesting is why it needs fixing after crafting, since that was working in 1.19 🤔

**Comment by WaxenSs** [comment]
Yes, it is strange.. But now, my compass is working perfectly!

**Comment by oddlama** [comment]
I'll see if I can reproduce this somehow, maybe something weird changed between versions that I'm not aware of. Ideally it shouldn't need to be dropped to start working 😅

**Comment by TDuffinNTU** [comment]
FWIW I ran into this issue when giving myself the item with commands/creative, but in survival I crafted it and it worked fine. Could be that commands/creative don't give the correct compass for the dimension you're in!
