### ISSUE TITLE
Command/Chat Area not showing up after install this plugin

### ISSUE THREAD

**Issue by gnattu** [oddlama/vane#2]
The ones used: core, bedtime, trifles, enchantments

enchantements is disabled, install it just because core depends on that.

After install this plugin, the left bottom command/chat area becomes invisible, user can still use command and chat, but the command outputs, include essential's motd, never shows up.

**Comment by oddlama** [comment]
This is because in the default config of vane-core, the option `message_delaying.enable` is set to `true`.
What this does is to prevents messages from reaching a players, before they have successfully loaded the server resource pack.
This is important as localized messages will not work properly if the serverv resourcepack is not yet loaded.

You can disable message delaying in the configuration to fix the problem. But beware that this most likely also means that you haven't set up the required resourcepack for the localized messages, which will make all plugin messages turn out as some seemingly random strings like `vane_core.some_message`. Althout it will be fine if you manually get the resource pack on your clients. (You can look at the Installation section in the README for more infos on the resource pack)
