### ISSUE TITLE
Infinite durability issues with old scrolls from before the 1.21 update.

### ISSUE THREAD

**Issue by FaultyFunctions** [oddlama/vane#276]
Old scrolls before the update are experiencing issues where the durability will only go down by 1, but they will stay at that level forever. They won't break and when the user logs out and back in, the durability is being set back to maximum. The console is showing `[vane-core] Updated item durability vane_trifles:home_scroll` when this happens. Any ideas what's going on?

**Comment by FaultyFunctions** [comment]
Also happens on opening scrolls in an enderchest. Something is failing in the `vane/vane-core/src/main/java/org/oddlama/vane/core/item/ExistingItemConverter.java` script in the `process_inventory` function.

**Comment by oddlama** [comment]
Yes you are right, the old values seem to be persisted after converting to the new vanilla durability system. And then they are converted each time which resets the durability to the old value.

Thanks for noticing, will be fixed in the next release (when PaperMC releases a stable 1.21.3 in the coming days) :)
