### ISSUE TITLE
Feature: Portal Channels

### ISSUE THREAD

**Issue by pokemonrocks9** [oddlama/vane#28]
Can we get a feature perhaps for channels that portals can link on so a group of friends can use them without others?

**Comment by oddlama** [comment]
If I understood your request correctly, I think this is already in the game.

When a portal is placed inside a region, you can set the portal visibility to `group` (not to be confused with `group internal`), which will only allow people to use the portal that have the corresponding permission in the region. This way, the portal can
be seen from any other portal but only if the user has the correct permission for the target portal.

If it is set to the previously mentioned `group internal`, the portal can be further restricted so that it only shows up on other portals in the same region group, which would more or less create a group of portals that can see each other but are hidden to the outside world.

You can configure who are your friends in the corresponding region group. Does this answer your question?

**Comment by oddlama** [comment]
@pokemonrocks9 I haven't heard back from you for a while, so I will now close this issue. If you would like to add anything, feel free to reply to the closed issue.

**Comment by pokemonrocks9** [comment]
Appears to work properly. We are just hoping on the method to administrate
it.

**Comment by oddlama** [comment]
Can you elaborate on what you are hoping? I'm not sure I understand the context correctly.

**Comment by pokemonrocks9** [comment]
I think I described in another issue already but hoping an ability to delete an abandoned portal or region without going into configs so it's able to be administrated in some way, and so we don't have people putting regions where they shouldn't. (We already have GP but regions is wanted to be enabled once it can be administrated specifically so we can have portal channels.)

**Comment by oddlama** [comment]
Ah I see, thanks for clarifying. The next two months I'm a little busy unfortunately, that's why I left your other issue open for the time being. But If all goes well I will have time to implement all the open feature requests afterwards.

**Comment by pokemonrocks9** [comment]
Take your time. We appreciate the support and the plugin is still amazing
and unique.
