### ISSUE TITLE
[Feature Suggestion] Portals

### ISSUE THREAD

**Issue by RozeFound** [oddlama/vane#33]
Your plugins is awesome to vanilla+ stuff.
What I want to suggest, it's portals for entities (like villagers), and an option to never close the portal automatically (it's a bit annoying re-open the portal every time I'm wanna go thrugh it)

**Comment by oddlama** [comment]
I'm glad you like it. Unfortunately there currently is no straightforward way of implementing portals for entities other than players, as the server doesn't expose any events for this. These events are most probably not exposed due to performance reasons. Although it's still certainly possible to implement, but might take a bit of tinkering on my side. I guess due to popular demand I can have a look at it.

Regarding the constantly open portal, there is another issue: When a portal is active, the chunks of the source and target portal must be loaded actively to allow for smooth travel and to avoid state inconsistencies. This means implementing a feature like always open portals can have a significant hit on server performance if there are several pairs of these permanently connected portals, which is why I dismissed the suggestion until now.

But there is a kind of workaround that is currently not documented anywhere:
You can control portal activation via redstone, if the portal is publicly usable. Point a repeater into any of the non-destroyable portal blocks and send a rising signal. This will activate it just like a lever would (it will deactivate automatically). This allows you to use sculk sensors or pressure plates to activate portals when a player approaches. Feel free to provide feedback on whether this is a sufficient alternative or you think another solution would be better.

**Comment by RozeFound** [comment]
For constantly open portals you can add a special permission. It will give an possibility to moderate this kind of portals and as follows performance hit.

**Comment by oddlama** [comment]
There are some subtle details that I haven't quite figured out how to solve yet. A permission would of course be a possible option for moderation, but I'd like to think this through properly before committing to any particular option. I'm of course open for any suggestions regarding the matter.

**Comment by RozeFound** [comment]
So I have nothing more to add. I'll just say good luck and thanks to your awesome plugins again
