### ISSUE TITLE
Upload in bukkit/spigot?

### ISSUE THREAD

**Issue by Siriusmart** [oddlama/vane#4]
Please upload this at bukkit or spigot so this plugin can be added to aternos plugin list

I rly want to use this :(

**Comment by oddlama** [comment]
Hi there!

The information I could gather on Aternos suggests that whether or not a plugin is added to the Aternos plugin list is fully determined by the Aternos Team. You are right that they require a download location on spigotmc or curseforge, but they also states the following:

>Mods/plugins should have reasonable popularity before they are added to Aternos. If a mod/plugin was published only a few >days ago or only has a few downloads, it won't be added.

While vane exists for more than a few days, I am certain it cannot be considered popular at by any means.
Nonetheless I have now uploaded the plugin to Curseforge ([here](https://www.curseforge.com/minecraft/bukkit-plugins/vane), will probably take some time before it is approved and publicly visible). But beware, that currently all vane plugins **require PaperMC** and will not run on regular Spigot servers.

Unfortunately, with the current situation I don't see this plugin being approved on Aternos anytime soon, due to the more complicated installation and the popularity requirement. If you want to
use it in time you probably need to work around the issue somehow.

**Comment by oddlama** [comment]
Plugin should now be available on curseforge.
