### ISSUE TITLE
Not working at offline mode server?

### ISSUE THREAD

**Issue by Acercars** [oddlama/vane#42]
Hello, I'm creating a new server to play with some friends, I got the host and I was configuring the plugins and so on. 
Everything seemed to work perfectly even permissions groups as admin and users. The problem was when I realized that two of our friends doesn't have the official version of minecraft so I set up the server as offline mode and when we get on the server nothing worked, I as an admin can't use any command and neither my friends or me can destroy blocks, being attacked or attack others.
Is there some option that I have missed or is it supposed to work like that?
I hope I have explained myself correctly as English is not my first language ...
Thank yoy very much for your time and for this amazing plugin <3

**Comment by oddlama** [comment]
When you change into offline mode, all players will have different UUIDs as opposed to the online mode. When you change from offline to online or vice versa, you will now have sort of "clashing" name to UUID mappings.

This means that any previously configured permissions are for the old "online" player profile and not for the new offline one. Also all commands taking a player name may resolve to the wrong old player profile rendering them useless.

As this is caused by switching to offline mode and not by vane, you can only resolve this manually.
You need to remove all player .dat files from `world/playerdata/`, where the uuid is from an online profile to avoid minecraft resolving the player name to the old uuid in commands. Also all settings you made in vane are saved with uuids for players, where you will now have the old uuids. This shouldn't be a problem per se, but you will have to redo all vane related commands that involve playrs, like adding all players to their corresponding groups again.

**Comment by Acercars** [comment]
Oooh, now I understand everything. Thank you so much, I fixed it with what you said.  Sorry to publish the post being that it was not a bug of this plugin, I was just so confused... Again, thank you!
