### ISSUE TITLE
-o not get build remapped!

### ISSUE THREAD

**Issue by TOWUK** [oddlama/vane#45]
https://github.com/oddlama/vane/blob/2a32f52124c60459e0a6e5597f69fc24b8e248e4/remap_patched_paper_for_development.sh#L13

LOL what is? `-o "${paper_jar/.jar/_remapped.jar}"` nice get file... but i dont get file...

**Comment by TOWUK** [comment]
good work!
![изображение](https://user-images.githubusercontent.com/28830162/131214480-83698b0c-2c99-400e-bb3a-62ee4f50d6f6.png)
Comment bodywhere should I search for your file?

**Comment by TOWUK** [comment]
![изображение](https://user-images.githubusercontent.com/28830162/131214565-71385ea0-8cbe-4fe8-a8bf-9ee92c164d22.png)

**Comment by oddlama** [comment]
I'm sorry but it is absolutely unclear to me what you are asking. I know language can be a barrier to some, so if this is the case for you, I'd like to recommend using https://www.deepl.com/translator, which can provide translations on a quite high level.

Also please stick to one issue instead of opening multiple ones for the same problem.

**Comment by oddlama** [comment]
Feel free to clarify under the closed issue, and I will reopen it.
