### ISSUE TITLE
Cannot see chat after installing vane plugins

### ISSUE THREAD

**Issue by Emilorzz** [oddlama/vane#6]
Hello, I just installed the vane plugin on my server, and it works great! It's just that i cannot see the chat at all. It's as if it's disabled.

**Comment by oddlama** [comment]
Have you correctly followed the [installation guide](https://github.com/oddlama/vane/wiki/Installation-Guide)?
This problem ocurrs when both the internal resource pack distribution and the message delayer are active (see `vane-core/config.yml`), but a player rejects the resource pack offered by the server.

The client usually needs time to load the resource-pack, but the server may already send chat messages to the client.
These messages cannot be formatted correctly before the resource-pack is fully loaded on the client, so vane will queues any chat message sent to a player until the client reports that the pack is loaded.

If a player rejects the resource-pack, no messages will ever be sent to the client. This is an issue with your installation, but I will implement a warning message in the next version.

**Comment by oddlama** [comment]
Leaving this issue open until the warning is implemented and released.

**Comment by oddlama** [comment]
I have just published a fix together with detection of bad configuration like this in release v1.1.2. Please update.

**Comment by Emilorzz** [comment]
Hello again! 

I simply hadn't followed the guide properly. Although i am having a problem of getting the resource pack to load. I hosted the pack via dropbox, and have put the link and sha-1 hash in the vane-core config, but when I try to join the server, I'm met with the message "_Your resource pack download seems to have failed._" The server is distributing the resource pack.

**Comment by oddlama** [comment]
Hmm, this is already outside of the territory of vane. The actual downloading of the pack is fully done by the client. The client only tells the server afterwards if it succeded or failed, and it said it failed, so vane will display that message.

To investigate what happens exactly, have a look at your client's log file. I've had similar issues the first time I tested the feature on my server, and finally came to the conclusion that minecraft has a problem downloading from "https://" links. Maybe it's the same for you, so you can try if dropbox supports http. Otherwise, I guess you will have to investigate what the client's log has to say about this.

**Comment by Emilorzz** [comment]
Alright, thanks for clearing that up!

 I've turned off the resource pack distribution for now, and manually applied it to my game, and am able to join the server. But I cannot interact with anything? I don't have the vane permissions installed so I don't believe that could have anything to do with it.

**Comment by oddlama** [comment]
There is a default spawnprotection for non-admins 64 blocks around 0 0 (see the FAQ entry in the readme).
If you don't use vane-permissions you must give players the correct permissions as shown in the install guide.
