### ISSUE TITLE
Enchantments not shown anymore

### ISSUE THREAD

**Issue by antonstech** [oddlama/vane#85]
![image](https://user-images.githubusercontent.com/58666027/147295065-3fcfcc4d-748d-4849-8beb-ee4b14eed137.png)
![image](https://user-images.githubusercontent.com/58666027/147295092-69a554d2-6488-4664-b58a-cb716d006949.png)

**Comment by oddlama** [comment]
Already tracked by #82

**Comment by oddlama** [comment]
I tried to reproduce this today, but wasn't able to. I figure you must have some other plugin installed that interferes with item lore, or a client side mod that strips the information. Could you show me the NBT data from a broken book (`/data get entity yourplayername SelectedItem` while holding it in your hand)?

**Comment by antonstech** [comment]
@oddlama has the following entity data: `{id: "minecraft:enchanted_book", tag: {StoredEnchantments: [{id: "vane_enchantments:soulbound", lvl: 1s}]}, Count: 1b}`

**Comment by ryantheleach** [comment]
@antonstech can you provide a list of plugins or a timings scan or something?

Does this affect all villagers, or just some?

Does this still affect brand new librarians?

**Comment by oddlama** [comment]
Most probably something else is doing that. I can see no valid reason how this could be caused by vane.

**Comment by antonstech** [comment]
@ryantheleach @oddlama I am using https://github.com/pufferfish-gg/Pufferfish and i have nothing installed except the Vane Plugins, Bluemap, Chunky. ProtocolLib, ServerBackup, TAB and Ultimate Homes

**Comment by oddlama** [comment]
You case is strange for two reasons:

- Even in older versions, vane removes generated custom enchantments from villager trades. So getting a soulbound book is impossible except when other plugin interfere with the events. (In the upcoming version it will be absolutely impossible that such a trade is even generated in the first place)
- The lore is missing. Can only be a result of another plugin or server software stripping the lore that was added by vane, probably due to incompatibility of that other software with chat components. Could also be caused by another plugin generating the specific trade and therefore not calling vane's internal function to update lore.

Both parts suggest an error with external software. I'm not sure what Pufferfish, or some of your other plugins do exactly, but I'm afraid that there is nothing we can do at the moment.
