### ISSUE TITLE
Suggestion: (vane-portals) allow leashed entities, pets, horses to come with you.

### ISSUE THREAD

**Issue by ryantheleach** [oddlama/vane#91]
At the moment the portals are dismounting entities the player is attached/riding/leashed to. it would be cool to see them come with the player.

**Comment by oddlama** [comment]
I'd love that, and most importantly it should be possible. Ideally I'd like to see all entities being able to traverse portals,
but this is not possible because there is no entity movement event in papermc (sad).

All entities that are somehow "attached" to a player could get teleported together with the player tough.
Would be a nice first contribution as I think this is easy to implement.

**Comment by oddlama** [comment]
Could be implemented together with #37
